FROM python:3.11-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código
COPY . .

# Comando para iniciar o worker do Celery
CMD ["celery", "-A", "app.core.celery_app", "worker", "--loglevel=info"]
